services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - '7700:7700'
    env_file:
      - .env
    volumes:
      - meilisearch_data:/meili_data

  embddings:
    image: sirtomasson/embddings
    ports:
      - '8000:8000'
    volumes:
      - embddings_data:/app/huggingface

volumes:
  meilisearch_data:
  embddings_data:
